apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-user-password
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: "homarr-user-password"
      property: password
  - secretKey: dbUrl
    remoteRef:
      key: "homarr-user-password"
      property: dbUrl
  - secretKey: username
    remoteRef:
      key: "homarr-user-password"
      property: username