kind: Service
apiVersion: v1
metadata:
  name: plex-service
  namespace: media
spec:
  selector:
    app: plex
  externalTrafficPolicy: Local
  ports:
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400
      # nodePort: 32400
  # type: LoadBalancer
