---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespaces.yaml
  # Flux-Kustomizations
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./agentgateway/ks.yaml
