apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway
  namespace: network
spec:
  chartRef:
    kind: OCIRepository
    name: agentgateway
    namespace: flux-system
  interval: 3m
  values:
    controller:
      extraEnv:
        KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES: "true"