---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 3m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: gateway-api-crds
  path: "./config/crd/experimental"
  prune: true
  wait: false
  timeout: 2m
  force: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app agentgateway-crds
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/network/agentgateway/agentgateway-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 3m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: gateway-api-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app agentgateway
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/network/agentgateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 3m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: agentgateway-crds
  

