apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway-crds
  namespace: network
spec:
  chartRef:
    kind: OCIRepository
    name: agentgateway-crds
    namespace: flux-system
  interval: 3m
  # values:
