---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: resume 
  namespace: gregbob
spec:
  hostnames:
  - resume.gregbob.net
  parentRefs:
  - name: wildcard-gregbob-net
    namespace: network
  rules:
  - backendRefs:
    - name: resume-service
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /