apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-homarr
  namespace: cnpg-system
spec:
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: homarr-superuser-password
  instances: 1
  bootstrap:
    initdb:
      database: homarrdb
      owner: homarr
      dataChecksums: true
      secret:
        name: homarr-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  resources:
    requests:
      memory: 500Mi
      cpu:  500m
    limits:
      memory: 500Mi
      cpu: 500m
  storage:
    size: 5Gi
    storageClass: ceph-block
